name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout develop-builds

      - name: Merge branches
        run: git merge develop develop-builds -m "Merge branch develop into develop-builds"

      - name: Install dependencies
        run: npm ci

      - name: Translate and Build
        run: |
          npm run translate
          npm run prepublish

      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Blocks build"
          git push
